version: "3"

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - "/data/koot-clinic"
  koot-clinic:
    image: docker.io/cmux/koot-clinic:0.0.1
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - "/data/koot-clinic"